
{'date': 'Mon Aug 06 2018 17:46:31.356 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    Museu()
TypeError: 'module' object is not callable
'''},
{'date': 'Mon Aug 06 2018 18:55:33.235 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from stacy.main import Museu
  module stacy.main line 78
    TUT=[
NameError: name 'sala_1' is not defined
'''},
{'date': 'Mon Aug 06 2018 19:36:15.276 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 7
    cena.vai()
  module stacy.main line 102
    Museu.CUR.instrumenta(self)
AttributeError: 'Cena' object has no attribute 'instrumenta'
'''},
{'date': 'Mon Aug 06 2018 19:40:54.895 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 7
    cena.vai()
  module stacy.main line 103
    Museu.CUR.instrumenta(self)
  module stacy.main line 99
    self.cod.entra(cena)
  module _spy.vitollino.main line 456
    self.scorer.update(valor=cena.nome, move=self.xy,
AttributeError: 'Museu' object has no attribute 'nome'
'''},
{'date': 'Mon Aug 06 2018 19:45:38.957 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 7
    cena.vai()
  module stacy.main line 104
    Museu.CUR.instrumenta(self)
  module stacy.main line 100
    self.cod.entra(cena)
  module _spy.vitollino.main line 459
    cena <= self
TypeError: '<=' not supported between instances of 'Museu' and 'Codigo'
'''},
{'date': 'Mon Aug 20 2018 08:34:30.611 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 7
    cena.vai()
  module stacy.main line 104
    Museu.CUR.instrumenta(self)
  module stacy.main line 100
    self.cod.entra(cena)
  module _spy.vitollino.main line 459
    cena <= self
TypeError: '<=' not supported between instances of 'Museu' and 'Codigo'
'''},
{'date': 'Mon Aug 20 2018 08:34:53.212 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    Museu()
  module stacy.main line 97
    entrada.vai()
  module stacy.main line 104
    Museu.CUR.instrumenta(self)
  module stacy.main line 100
    self.cod.entra(cena)
  module _spy.vitollino.main line 459
    cena <= self
TypeError: '<=' not supported between instances of 'Museu' and 'Codigo'
'''},
{'date': 'Fri Apr 26 2019 08:44:43.442 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 7
    cena.vai()
  module stacy.main line 104
    Museu.CUR.instrumenta(self)
  module stacy.main line 100
    self.cod.entra(cena)
  module _spy.vitollino.main line 465
    cena <= self
TypeError: '<=' not supported between instances of 'Museu' and 'Codigo'
'''},
{'date': 'Fri Apr 26 2019 08:45:00.747 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    Museu()
  module stacy.main line 97
    entrada.vai()
  module stacy.main line 104
    Museu.CUR.instrumenta(self)
  module stacy.main line 100
    self.cod.entra(cena)
  module _spy.vitollino.main line 465
    cena <= self
TypeError: '<=' not supported between instances of 'Museu' and 'Codigo'
'''},