
{'date': 'Mon Aug 13 2018 11:14:18.225 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 76
  Sala3D()
  ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Aug 13 2018 11:14:51.367 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 77
    Sala3D()
TypeError: __init__() missing 1 positional argument: ['img_list']
'''},
{'date': 'Mon Aug 13 2018 11:17:53.983 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 68
    doc['pydiv'].html = ''
NameError: name 'doc' is not defined
'''},
{'date': 'Mon Aug 13 2018 12:00:53.981 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
Exception: origin.equals is not a function
  module '$exec_1904' line 85
Sala3D(IMG_LIST)
'''},
{'date': 'Mon Aug 13 2018 12:06:31.413 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
Exception: origin.equals is not a function
  module '$exec_459' line 85
Sala3D(IMG_LIST)
'''},
{'date': 'Mon Aug 13 2018 12:19:16.49 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 78
  parede_ = box(pos=(2*POS[direcao][0], 2*POS[direcao][1]), 0, size=(0.2, 2, 2), texture=dict(file=parede, place=["right"]))
                                                             ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Mon Aug 13 2018 13:19:20.999 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 87
    Sala3D(IMG_LIST)
  module <module> line 77
    local_light(pos=(0,0,4))
NameError: name 'local_light' is not defined
'''},
{'date': 'Mon Aug 13 2018 14:01:21.976 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 2
  MUSEU = dict(
                                                                                                             ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 13 2018 14:02:08.732 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 70
    IMG_LIST = [C0_NORTE, C0_LESTE, C0_SUL, C0_OESTE]
NameError: name 'C0_NORTE' is not defined
'''},
{'date': 'Mon Aug 13 2018 14:40:50.451 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 72
    IMGS = [[MUSEU["C{:01X}{}".format(sala, rosa)] for rosa in ROSA] for sala in range(16)]
KeyError: CF_NORTE
'''},
{'date': 'Mon Aug 13 2018 18:55:32.124 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 104
    Museu()
  module <module> line 91
    Elemento(sala, style = dict(left=i*20, top =j*20, width=18, height="18px")).entra(cena)
NameError: name 'Elemento' is not defined
'''},
{'date': 'Mon Aug 13 2018 18:56:39.310 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 104
    Museu()
  module <module> line 91
    Elemento(prd, style = dict(left=i*20, top =j*20, width=18, height="18px")).entra(cena)
NameError: name 'Elemento' is not defined
'''},
{'date': 'Mon Aug 13 2018 19:05:37.811 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 104
    Museu()
  module <module> line 88
    cena = Cena(C9_OESTE)
NameError: name 'C9_OESTE' is not defined
'''},
{'date': 'Wed Aug 15 2018 11:44:04.757 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 105
  CD_LESTE = "https://i.imgur.com/dtzdhIy.jpgâ,
                                                 ^
SyntaxError: EOL while scanning string literal
'''},